version: "2"
services:
  tw-api:
    container_name: tw-api
    restart: always
    build: .
    ports:
      - "8080:8080"
    links:
      - mongo
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./mongodata:/data/db
    ports:
      - "27017:27017"
